baseURL = 'https://jiaozi789.github.io/docs'
languageCode = 'en-us'
publishDir = "docs"
title = 'liaomin416100569博客'
theme = 'relearn'
[params]
  custom_css = ["css/custom.css"]

[markup.tableOfContents]
startLevel = 1
endLevel = 4   # 默认是 3，你可以改成 4 或更高